### ISSUE TITLE
The variant of the rename() that accepts an dictionary fails

### ISSUE THREAD

**Issue by chathurawidanage** [cylondata/cylon#344]
grouped_inv_dates = grouped_inv_dates.rename({
    "mean_inv_quantity_on_hand":"qty_mean"
})

Traceback (most recent call last):
  File "tpcx__bb_query_23.py", line 60, in <module>
    grouped_inv_dates = grouped_inv_dates.rename({
  File "pycylon/data/table.pyx", line 1935, in pycylon.data.table.Table.rename
  File "pycylon/indexing/index.pyx", line 70, in pycylon.indexing.index.BaseIndex.index_values.__get__
  File "pycylon/indexing/index.pyx", line 62, in pycylon.indexing.index.BaseIndex.get_index_array
  File "pyarrow/public-api.pxi", line 196, in pyarrow.lib.pyarrow_wrap_array
ValueError: Array was NULL

**Comment by vibhatha** [comment]
@chathurawidanage 

How does the initial table get created? 
From File or by an intermediate operation? 

The issue is incoperating indexing with all ops. At the moment you can set a range index by 


index_arr = [i for i in range(0, data_table.row_count)
data_table.set_index(index_arr)

**Comment by chathurawidanage** [comment]
What if I don't need indexing?

**Comment by vibhatha** [comment]
You don't need to give it externally, this must be handled internally. 
At the moment, all the operations are not indexing aware (handling indexing within the framework), this is a work in progress. 
Even if you don't need an index, in pandas the default index is always there. When we have to support the operations in this manner, we need to keep the index.

**Comment by nirandaperera** [comment]
I'm also having this issue now. 
IMO, this index getting and resetting should only be done on indices other than the default range index. 
https://github.com/cylondata/cylon/blob/8b1b536b55a81b9c79d9bf379eee948056bf688d/python/pycylon/data/table.pyx#L1881
https://github.com/cylondata/cylon/blob/8b1b536b55a81b9c79d9bf379eee948056bf688d/python/pycylon/data/table.pyx#L1895
